/** Original exercise descriptions for SculptAI's browsable catalog. */
export const additionalExercises = [
  ['Chest', 'Machine chest press', 'Gym', 'push', 'Set the seat so handles align with your chest. Press smoothly and return under control.'],
  ['Chest', 'Incline barbell press', 'Gym', 'push', 'Use a modest incline and a spotter or safeties. Lower to a comfortable depth.'],
  ['Chest', 'Pec deck fly', 'Gym', 'push', 'Set the handles within a comfortable range. Bring your arms together without shrugging.'],
  ['Chest', 'Incline push-up', 'Bodyweight', 'push', 'Place hands on a stable raised surface. Keep your body straight as you lower your chest.'],
  ['Chest', 'Dumbbell floor press', 'Dumbbells', 'push', 'Lie on the floor with knees bent. Lower until your upper arms gently touch the floor.'],
  ['Back', 'Chest-supported dumbbell row', 'Dumbbells', 'pull', 'Rest your chest on an incline bench. Row without lifting your torso from the pad.'],
  ['Back', 'Machine row', 'Gym', 'pull', 'Keep your chest supported and pull the handles toward your ribs. Return slowly.'],
  ['Back', 'Assisted pull-up', 'Gym', 'pull', 'Choose assistance that permits controlled reps. Pull without kicking or swinging.'],
  ['Back', 'Straight-arm cable pulldown', 'Gym', 'pull', 'Maintain soft elbows and pull the bar toward your thighs without rocking your torso.'],
  ['Back', 'Barbell row', 'Gym', 'pull', 'Hinge at your hips and brace your torso. Pull toward your lower ribs without jerking.'],
  ['Shoulders', 'Cable lateral raise', 'Gym', 'push', 'Raise your arm to a comfortable height with a soft elbow. Lower slowly.'],
  ['Shoulders', 'Reverse pec deck', 'Gym', 'pull', 'Keep your chest against the pad. Open your arms without arching your back.'],
  ['Shoulders', 'Seated dumbbell press', 'Dumbbells', 'push', 'Sit supported and press with wrists stacked above elbows. Avoid arching your lower back.'],
  ['Biceps', 'EZ-bar curl', 'Gym', 'pull', 'Keep your upper arms near your sides. Curl without using your hips for momentum.'],
  ['Biceps', 'Rope cable hammer curl', 'Gym', 'pull', 'Hold the rope with palms facing in. Keep elbows steady as you curl.'],
  ['Biceps', 'Alternating dumbbell curl', 'Dumbbells', 'pull', 'Alternate arms with a controlled lowering phase. Keep the resting arm still.'],
  ['Triceps', 'Rope overhead cable extension', 'Gym', 'push', 'Keep upper arms steady near your head. Extend your elbows without arching your back.'],
  ['Triceps', 'Lying dumbbell triceps extension', 'Dumbbells', 'push', 'Lie supported and keep upper arms steady. Bend and extend the elbows with light weights.'],
  ['Triceps', 'Close-grip bench press', 'Gym', 'push', 'Use a comfortable narrow grip and safeties or a spotter. Keep wrists stacked.'],
  ['Forearms', 'Dumbbell reverse wrist curl', 'Dumbbells', 'pull', 'Support your forearms with palms down. Lift and lower the wrists gently.'],
  ['Forearms', 'Reverse EZ-bar curl', 'Gym', 'pull', 'Use an overhand grip and a light load. Keep elbows close and wrists steady.'],
  ['Legs', 'Leg press', 'Gym', 'leg', 'Keep your back supported and feet grounded. Stop before your pelvis rolls away from the pad.'],
  ['Legs', 'Leg extension', 'Gym', 'leg', 'Align the machine pivot with your knees. Extend smoothly without kicking or locking forcefully.'],
  ['Legs', 'Seated leg curl', 'Gym', 'hinge', 'Adjust the pad above your heels. Curl with control while keeping your hips on the seat.'],
  ['Legs', 'Dumbbell step-up', 'Dumbbells', 'leg', 'Use a stable low platform. Push through the lead foot and lower with control.'],
  ['Legs', 'Dumbbell reverse lunge', 'Dumbbells', 'leg', 'Step backward into a comfortable stance. Keep your front foot grounded.'],
  ['Glutes', 'Barbell hip thrust', 'Gym', 'hinge', 'Support your upper back on a stable bench. Lift your hips without overextending your back.'],
  ['Glutes', 'Cable glute kickback', 'Gym', 'hinge', 'Keep your torso steady and extend your hip through a comfortable range.'],
  ['Glutes', 'Dumbbell hip thrust', 'Dumbbells', 'hinge', 'Secure the weight over your hips. Lift through your feet and lower slowly.'],
  ['Glutes', 'Side-lying leg raise', 'Bodyweight', 'leg', 'Keep your hips stacked. Raise the top leg without rolling backward.'],
  ['Calves', 'Seated calf raise', 'Gym', 'leg', 'Keep the balls of your feet on the platform. Raise and lower your heels slowly.'],
  ['Calves', 'Standing machine calf raise', 'Gym', 'leg', 'Keep your knees soft and pause at the top. Use a comfortable stretch at the bottom.'],
  ['Calves', 'Single-leg calf raise', 'Bodyweight', 'leg', 'Use a stable support for balance. Lift and lower with control on each side.'],
  ['Abs', 'Cable crunch', 'Gym', 'core', 'Round your torso gently through your abdomen. Avoid pulling down with your arms.'],
  ['Abs', 'Bird dog', 'Bodyweight', 'core', 'From hands and knees, extend opposite arm and leg without arching your back.'],
  ['Abs', 'Side plank hip lift', 'Bodyweight', 'core', 'Keep your shoulder stacked over your elbow. Lift your hips with control on each side.'],
  ['Abs', 'Pallof press', 'Gym', 'core', 'Stand side-on to a cable. Press forward while resisting rotation of your torso.'],
  ['Cardio', 'Brisk walking', 'Bodyweight', 'cardio', 'Walk at a pace that raises your breathing while you can still talk but not sing.'],
  ['Cardio', 'Easy jogging', 'Bodyweight', 'cardio', 'Jog at a comfortable pace and slow to a walk if needed.'],
  ['Cardio', 'Marching in place', 'Bodyweight', 'cardio', 'March with relaxed shoulders and a steady rhythm; use a wall for balance if needed.'],
  ['Cardio', 'Stationary cycling', 'Gym', 'cardio', 'Adjust the seat for a comfortable knee bend and pedal at a steady, manageable pace.'],
  ['Cardio', 'Elliptical training', 'Gym', 'cardio', 'Keep your feet on the pedals and move smoothly at a pace you can sustain.'],
  ['Cardio', 'Rowing machine', 'Gym', 'cardio', 'Drive through your legs, then lean back slightly and pull; reverse the order to return.'],
  ['Cardio', 'Incline treadmill walking', 'Gym', 'cardio', 'Start at a gentle incline and hold a pace that lets you maintain control.'],
  ['HIIT', 'Fast march intervals', 'Bodyweight', 'hiit', 'March briskly during each work interval, then slow down to recover.'],
  ['HIIT', 'Step jack intervals', 'Bodyweight', 'hiit', 'Step one foot out at a time as your arms rise; avoid jumping if you prefer low impact.'],
  ['HIIT', 'Shadow boxing intervals', 'Bodyweight', 'hiit', 'Throw light controlled punches into the air while keeping your knees soft.'],
  ['HIIT', 'High knee intervals', 'Bodyweight', 'hiit', 'Lift your knees only as high as comfortable; reduce to a march when needed.'],
  ['HIIT', 'Mountain climber intervals', 'Bodyweight', 'hiit', 'Keep your hands supported and step or drive one knee forward at a time without letting your hips sag.'],
  ['HIIT', 'Stationary bike intervals', 'Gym', 'hiit', 'Increase your pedaling effort for the work interval, then pedal easily during recovery.'],
  ['HIIT', 'Rowing machine intervals', 'Gym', 'hiit', 'Row with controlled form during work intervals and easy strokes during recovery.'],
].map(([group, name, equipment, pattern, cue]) => ({ group, name, equipment, pattern, cue }));
