import { test } from 'node:test';
import assert from 'node:assert/strict';
import { applyAction } from './actions.ts';
import { emptyState, nutrition, type Metric, type Profile } from './fitness.ts';
import { analyzeFuelTrend, analyzeFuelTimeline } from './fuel-coach.ts';
import { applyCoachFuelReview, applyCoachTimeline, fuelNeedsSync, fuelReviewDue, weightTrend } from './fuel-adaptation.ts';
const profile: Profile = { name:'Tester', age:30, sex:'Male', height:175, weight:75, targetWeight:78, goal:'Muscle gain', days:3, minutes:45, equipment:'Gym', experience:'Intermediate', activity:1.375, units:'Metric', diet:'Omnivore', exclusions:'', avoid:'', eligible:true };
const today = new Date().toISOString().slice(0,10);
const day = (offset: number) => new Date(Date.parse(today) - offset * 864e5).toISOString().slice(0,10);
const metrics = [21,18,15,6,3,0].map((offset,index): Metric => ({id:`m${index}`,date:day(offset),weight:75+index*.15,source:'Manual',notes:''}));
void test('Fuel updates from profile and newest check-in while retaining target history', () => {
  let state=applyAction(emptyState(),{type:'profile',profile});
  assert.equal(state.targets.length,1);
  const original=state.targets[0];
  state=applyAction(state,{type:'metric',metric:{date:today,weight:76,source:'Manual',notes:''}});
  assert.equal(state.targets.length,2);
  assert.equal(state.targets.at(-1)?.inputs.weight,76);
  assert.notEqual(state.targets.at(-1)?.calories,original.calories);
  assert.equal(state.targets[0].inputs.weight,75);
  assert.equal(fuelReviewDue(state),null);
  assert.equal(fuelNeedsSync(state),false);
  const older = { ...state, targets: [original] };
  assert.equal(fuelNeedsSync(older),true);
});
void test('Coach waits for multiple weeks, limits adjustments, and cannot update twice immediately', async () => {
  assert.equal(weightTrend(metrics.slice(0,5)),null);
  const state=applyAction(emptyState(),{type:'profile',profile});
  state.metrics=metrics;
  const trend=fuelReviewDue(state);
  assert.ok(trend);
  const fake: typeof fetch = async () => Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({delta:100,explanation:'Trend shows slow gain; review after two more weeks.'})}]}]});
  const review=await analyzeFuelTrend(state,{OPENAI_API_KEY:'test-key',OPENAI_MODEL:'test-model'},fake);
  assert.equal(review?.delta,100);
  applyCoachFuelReview(state,review!.delta,review!.explanation);
  assert.equal(state.targets.at(-1)?.source,'ai-coach');
  assert.equal(state.targets.at(-1)?.adjustment,100);
  assert.equal(fuelReviewDue(state),null);
  assert.throws(() => applyCoachFuelReview(state,150,'Too much'));
});
void test('Target weight controls goal calories and timeline without claiming current intake', () => {
  assert.throws(() => applyAction(emptyState(), {type:'profile',profile:{...profile,targetWeight:0}}), /Target weight/);
  const gain = applyAction(emptyState(),{type:'profile',profile});
  assert.ok(gain.targets[0].calories > gain.targets[0].maintenance);
  assert.ok(gain.targets[0].timeline);
  const loss = applyAction(emptyState(),{type:'profile',profile:{...profile,targetWeight:72,goal:'Fat loss'}});
  assert.ok(loss.targets[0].calories < loss.targets[0].maintenance);
  assert.throws(() => applyAction(emptyState(),{type:'profile',profile:{...profile,targetWeight:45}}),/target weight/i);
  const reached = applyAction(gain,{type:'metric',metric:{date:today,weight:78,source:'Manual',notes:''}});
  assert.equal(reached.targets.at(-1)?.calories,reached.targets.at(-1)?.maintenance);
  assert.equal(reached.targets.at(-1)?.timeline,undefined);
});
void test('AI timeline is constrained to a broad server planning range', async () => {
  const state=applyAction(emptyState(),{type:'profile',profile});
  const bounds=state.targets[0].timeline!;
  const minWeeks=bounds.minWeeks+1,maxWeeks=bounds.maxWeeks-1;
  const fake:typeof fetch=async () => Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({minWeeks,maxWeeks,explanation:'Planning range; check-ins may change it.'})}]}]});
  const result=await analyzeFuelTimeline(state,{OPENAI_API_KEY:'test-key',OPENAI_MODEL:'test-model'},fake);
  assert.equal(result?.minWeeks,minWeeks);
  applyCoachTimeline(state,result!.targetId,result!.minWeeks,result!.maxWeeks,result!.explanation);
  assert.equal(state.targets[0].timeline?.source,'ai-coach');
  assert.throws(() => applyCoachTimeline(state,'other',1,2,'Invalid'));
});
void test('different lower target weights at the same current weight get different bounded calorie goals', () => {
  const p = { ...profile, weight:80, goal:'Fat loss' };
  const near = nutrition({ ...p, targetWeight:75 });
  const far = nutrition({ ...p, targetWeight:59 });
  assert.equal(near.maintenance, far.maintenance);
  assert.ok(far.calories < near.calories && near.calories < near.maintenance);
  assert.ok(far.calories >= far.maintenance * 0.85);
  const legacy = { ...near, method:'Mifflin-St Jeor + activity; SculptAI v2.1', calories:near.maintenance*.9 };
  const state = { ...emptyState(), profile:{ ...p, targetWeight:75 }, targets:[legacy] };
  assert.equal(fuelNeedsSync(state), true);
  const updated = applyAction(state,{type:'fuelSync'});
  assert.equal(updated.targets.length,2);
  assert.equal(updated.targets.at(-1)?.calories,near.calories);
  assert.match(updated.targets.at(-1)?.analysis || '',/Recalculated with the goal-gap method/);
});
