/* oxlint-disable typescript/no-require-imports -- Local browser test tooling */
const {chromium}=require('C:/Users/aravi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const origin='http://localhost:3001';let browser,page;const checks=[],errors=[];
async function capture(step){await page.screenshot({path:'outputs/live-test.png',fullPage:false});fs.writeFileSync('outputs/test-status.json',JSON.stringify({step,updated:Date.now()}));console.log(step);}
async function check(name,fn){await fn();checks.push(name);await capture('Passed · '+name);}
async function choice(label,value){await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click();}
async function state(){const r=await page.request.get(origin+'/api/state');assert.equal(r.status(),200,await r.text());return r.json();}
async function run(){
 fs.mkdirSync('outputs',{recursive:true});browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:1000}});page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin,{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('link',{name:'Sign in / Sign up',exact:true}).waitFor();await capture('Checking visible sign-in and the lighter 3D human');
 await check('Anonymous access and forged identity are rejected',async()=>{assert.equal((await page.request.get(origin+'/api/state')).status(),401);assert.equal((await page.request.get(origin+'/api/state',{headers:{'oai-authenticated-user-id':'fake','oai-authenticated-user-email':'fake@example.test'}})).status(),401);});
 await check('3D model loads with no page errors',async()=>{await page.waitForFunction(()=>!!document.querySelector('canvas')&&!document.querySelector('.model-status')&&!document.querySelector('.model-fallback'),{},{timeout:30000});assert.equal(errors.length,0,errors.join('\n'));const sizes=await page.evaluate(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('athlete-optimized')).map(x=>({duration:Math.round(x.duration),bytes:x.decodedBodySize})));fs.writeFileSync('outputs/model-timing.json',JSON.stringify(sizes));await page.screenshot({path:'outputs/model-ready.png',fullPage:true});});
 await check('Sign in reaches a real private account',async()=>{await page.getByRole('link',{name:'Sign in / Sign up',exact:true}).click();await page.getByRole('button',{name:/Your account|SculptAI QA/}).waitFor();const d=await state();if(d.state.profile){if(d.state.profile.name!=='SculptAI QA')throw new Error('Local account already has non-test data; stopping to preserve it.');const r=await page.request.post(origin+'/api/state',{headers:{Origin:origin},data:{revision:d.revision,operationId:crypto.randomUUID(),action:{type:'deleteData',confirmation:'DELETE'}}});assert.equal(r.status(),200);await page.reload();await page.getByRole('button',{name:/Your account|SculptAI QA/}).waitFor();}});
 await check('Profile onboarding saves and opens training',async()=>{await page.getByRole('button',{name:'Set up your profile',exact:true}).click();await page.getByLabel('Preferred name',{exact:true}).fill('SculptAI QA');await page.getByLabel('Age (18+)',{exact:true}).fill('30');await choice('Primary goal','Muscle gain');await choice('Experience','Beginner');await choice('Training days / week','3');await choice('Minutes / session','45');await choice('Available equipment','Dumbbells');await choice('Diet preference','Vegetarian');await page.getByLabel('Height (cm) · optional',{exact:true}).fill('175');await page.getByLabel('Starting weight (kg) · optional',{exact:true}).fill('75');await choice('Sex used by formula (optional)','Male');await choice('Activity level','Lightly active');await page.getByRole('switch').check();await page.getByRole('button',{name:'Save profile',exact:true}).click();await page.getByRole('heading',{name:'Make today count.'}).waitFor();assert.equal((await state()).state.profile.name,'SculptAI QA');});
 await check('Plan preview requires confirmation and persists',async()=>{await page.getByRole('button',{name:'Create my plan',exact:true}).click();await page.getByRole('alertdialog').waitFor();assert.equal((await state()).state.plans.length,0);await page.getByRole('button',{name:'Confirm & save',exact:true}).click();await page.getByRole('button',{name:'Start workout'}).first().waitFor();assert.equal((await state()).state.plans.length,1);});
 await check('Workout entry autosaves repetitions, load and effort',async()=>{await page.getByRole('button',{name:'Start workout'}).first().click();await page.getByText('YOUR ACTIVE WORKOUT',{exact:false}).waitFor();const reps=page.locator('.set-entry input').nth(0),load=page.locator('.set-entry input').nth(1),rpe=page.locator('.set-entry input').nth(2);await reps.fill('12');await load.fill('20');await rpe.fill('7');await page.getByRole('heading').filter({hasText:'Bodyweight squat'}).count();await rpe.blur();await page.waitForFunction(()=>document.querySelector('.save-status')?.textContent==='All changes saved');await page.locator('.set-entry').first().getByRole('button',{name:/^Complete /}).click();await page.waitForFunction(()=>document.querySelector('.save-status')?.textContent==='All changes saved');const s=(await state()).state.sessions[0];assert.equal(s.sets[0].done,true);assert.equal(s.sets[0].load,20);});
 await check('Refresh recovers the active workout and logged set',async()=>{await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:/SculptAI QA/}).waitFor();await page.getByRole('tab',{name:'My training',exact:true}).click();await page.locator('.set-entry').first().waitFor();assert.equal(await page.locator('.set-entry input').nth(0).inputValue(),'12');assert.equal(await page.locator('.set-entry input').nth(1).inputValue(),'20');await page.locator('.set-entry').nth(1).getByRole('button',{name:'Skip',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.save-status')?.textContent==='All changes saved');await page.getByRole('button',{name:'Finish workout',exact:true}).first().click();await page.getByRole('button',{name:'Confirm & save',exact:true}).click();await page.getByRole('button',{name:'Start workout'}).first().waitFor();assert.equal((await state()).state.sessions[0].status,'partial');});
 await check('Weight check-in appears in history and charts',async()=>{await page.getByRole('tab',{name:'Insights',exact:true}).click();await page.getByRole('button',{name:'Add check-in',exact:true}).click();await page.getByLabel('Weight (kg)',{exact:true}).fill('75');await page.getByRole('button',{name:'Save check-in',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await state()).state.metrics[0].weight,75);await page.screenshot({path:'outputs/insights-desktop.png',fullPage:true});});
 await check('Nutrition target is reviewed, adopted and saved',async()=>{await page.getByRole('tab',{name:'Fuel',exact:true}).click();await page.getByRole('button',{name:'Calculate my targets',exact:true}).click();assert.equal((await state()).state.targets.length,0);await page.getByRole('button',{name:'Confirm & save',exact:true}).click();await page.getByText('DAILY ENERGY',{exact:true}).waitFor();assert.equal((await state()).state.targets.length,1);});
 await check('Guide responds using recorded history',async()=>{await page.getByRole('tab',{name:'Coach',exact:true}).click();await page.getByRole('button',{name:'Summarize my training',exact:true}).click();await page.getByRole('button',{name:'Ask your guide',exact:true}).click();await page.locator('.coach-response').waitFor();assert.match(await page.locator('.coach-response').innerText(),/0 complete and 1 partial/);});
 await check('Phone layout fits 320 pixels and controls remain reachable',async()=>{await page.setViewportSize({width:320,height:800});for(const tab of ['Studio','My training','Insights','Fuel','Coach']){await page.getByRole('tab',{name:tab,exact:true}).click();const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(width.scroll<=width.width+1,`${tab}: overflow ${width.scroll}/${width.width}`);}await page.getByRole('tab',{name:'Studio',exact:true}).click();await page.screenshot({path:'outputs/studio-mobile.png',fullPage:true});});
 await check('Sign out removes access to saved data',async()=>{await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:/SculptAI QA/}).click();await page.getByRole('link',{name:'Sign out',exact:true}).click();await page.getByRole('link',{name:'Sign in / Sign up',exact:true}).waitFor();assert.equal((await page.request.get(origin+'/api/state')).status(),401);});
 assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync('outputs/browser-results.json',JSON.stringify({checks,errors,passed:true},null,2));await capture(`${checks.length} browser checks passed · ready for review`);await browser.close();
}
run().catch(async e=>{console.error(e.stack);fs.writeFileSync('outputs/browser-results.json',JSON.stringify({checks,errors,error:e.message,passed:false},null,2));if(page)await capture('Investigating · '+e.message.split('\n')[0]).catch(()=>{});if(browser)await browser.close();process.exitCode=1;});
